platform :ios, '16.0'

target 'CocoaPodsExample' do
  use_frameworks!
  pod 'BlueTriangleSDK-Swift', :git => 'https://github.com/JP-aloha/btt-swift-sdk.git', :branch => 'net_capture_start_time_issue'
end
